<?php
// SISTEMA DE PEDIDOS ONLINE PARA FÁBRICA MAGAZIN ESTOFADOS, PLATAFORMA PARA REPRESENTANTES REALIZAREM PEDIDOS DE PRODUÇÃO RAPIDAMENTE 
		//SEM A NECESSIDADE DE ENVIO DE NOTAS À FABRICA 
header('Location: Login.php');
?>