<?php
// SISTEMA DE PEDIDOS ONLINE PARA FมBRICA MAGAZIN ESTOFADOS, PLATAFORMA PARA REPRESENTANTES REALIZAREM PEDIDOS DE PRODUวรO RAPIDAMENTE 
		//SEM A NECESSIDADE DE ENVIO DE NOTAS ภ FABRICA 
session_start();
session_destroy();
session_unset();
header('Location: Login.php');
?>